// LOCALHOST 

### Get all players 
GET http://localhost:8080/players

### Get contact by id 
GET http://localhost:8080/players/674afac5e8983a06c845b0c7

### Create contact 
POST http://localhost:8080/players 
content-type: application/json

 {
    "name": "James Lewis Reece",
    "gender":"male",
    "position": "Midfilder",
    "clubPlayed": [
      "Wigan Athletic FC",
      "Chelsea FC"
    ],
    "nationality": "Neitherland",
    "birthday": "08-12-1999",
    "height": "1.79m"
  }

### Update contact 
PUT http://localhost:8080/players/674de07707b540d78b878a11
content-type: application/json

 {
    "name": "James Lewis Reece",
    "gender":"male",
    "position": "Midfielder",
    "clubPlayed": [
      "Wigan Athletic FC",
      "Chelsea FC"
    ],
    "nationality": "Neitherland",
    "birthday": "08-12-1999",
    "height": "1.79m"
  }
### DELETE contact 
DELETE http://localhost:8080/players/6750e36c07b540d78b878a13

// PRODUCTION Deploy

### Get all contacts 
GET https://project-03-irq1.onrender.com/players

### Get contact by id 
GET https://project-03-irq1.onrender.com/players/6742c8bc2377efc2fbfd0392

### Create contact 
POST https://project-03-irq1.onrender.com/players
content-type: application/json

{
    "name": "Lamine Yamal",
    "gender": "male",
    "position": "Midfielder",
    "clubPlayed": [
      "FC Barcelona Atletic",
      "FC Barcelona",
    ],
    "nationality": "England",
    "birthday": "13-07-2007",
    "height": "1.8m"
  }
### Update contact 
PUT https://project-03-irq1.onrender.com/players/6742cb0f5bf84cdf85561140
content-type: application/json

{
    "name": "Lamine Yamal",
    "gender": "male",
    "position": "Midfielder",
    "clubPlayed": [
      "FC Barcelona Atletic",
      "FC Barcelona",
    ],
    "nationality": "England",
    "birthday": "13-07-2007",
    "height": "1.8m"
  }

### DELETE contact 
DELETE https://project-03-irq1.onrender.com/players/6750e42e07b540d78b878a14

